services:
  - type: web
    name: immigration-lawyer-rag-backend
    runtime: python
    buildCommand: pip install flask flask-cors requests
    startCommand: python render_light.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src 