services:
  - type: web
    name: legal-search-ai-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt &&
      cd legal-search-nextjs &&
      npm install &&
      npm run build
    startCommand: |
      cd legal-search-nextjs && npm run start &
      gunicorn app:create_app()
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production 